In [1]:
# Scientific libraries		              
import numpy as np		              
import scipy as sp		              
import pandas as pd		              
import json		              
import missingno as msno		              

# Loading Plotting Modules		              
import matplotlib		              
import matplotlib.pyplot as plt		              
import seaborn as sns		              
%matplotlib inline		              
import chart_studio.plotly as py		              
import plotly.figure_factory as ff		              
import plotly.graph_objects as go		              
import plotly.express as px		              
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot		              
init_notebook_mode(connected=True)		              
		              
import os		              
import gc

In [2]:
# Setting Data Frame Options                      
pd.set_option('display.max_rows', 40)                      
pd.set_option('display.max_columns', 50)                      
pd.set_option('display.width', 100)                      
pd.set_option('display.max_colwidth', 100)                      

# Setting Plot Configuration                      
sns.set(rc={'figure.figsize':(19,11)}, style = 'white')

In [3]:
train = pd.read_csv('../eda/outputs/imputed_train_mf.csv')                
m, n = train.shape                
print('Data Frame: {} x {}'.format(m,n))                
train.head()

Data Frame: 3865 x 80

,galactic year,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",...,"Estimated gross galactic income per capita, female",Rural population with access to electricity (%),Domestic credit provided by financial sector (% of GGP),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Gross fixed capital formation (% of GGP),"Remittances, inflows (% of GGP)",Population with at least some secondary education (% ages 25 and older),Intergalactic inbound tourists (thousands),"Gross enrolment ratio, primary (% of primary under-age population)","Respiratory disease incidence (per 100,000 people)",Interstellar phone subscriptions (per 100 people),"Interstellar Data Net users, total (% of population)",Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,Gender Inequality Index (GII),y,galaxy,Private galaxy capital flows (% of GGP),"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total"
0,990025.0,0.759989,72.020628,18445.323465,0.647025,13.819287,10.275156,0.700193,0.744757,172.455086,69.788964,56.534984,71.977811,779.140792,53.717993,136.148520,94.372591,13.486308,486.311516,46.744351,68.373831,70.009342,13.364702,97.579821,94.595420,...,NaN,101.154818,NaN,NaN,NaN,75.084941,16.992398,NaN,83391.283213,127.531343,585.233964,62.354315,31.610527,11.813392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.049214,Andromeda Galaxy (M31),55.482526,NaN
1,990025.0,0.588206,62.473456,12072.373320,0.614855,8.368089,5.066478,0.578664,0.548011,166.597596,65.947524,62.229056,34.832775,883.596591,41.490223,202.512345,138.465984,17.670232,307.683155,87.014838,64.812267,63.080870,49.771269,109.152114,167.570379,...,13010.736695,69.845859,76.245703,28.236492,63.468500,32.250699,1.544445,55.120787,114924.778620,111.219200,487.854193,74.369426,32.855526,6.259720,0.641545,0.664679,0.949618,143.210761,161.265976,12.692108,0.749825,0.053204,Andromeda I,25.466775,2.940205
2,990025.0,1.063381,93.576404,34891.830736,0.945705,15.452324,13.267036,1.013674,0.773926,63.933456,116.707970,122.187118,38.249852,1037.163377,92.323704,46.060790,28.403142,27.020113,385.343237,69.424835,90.226902,85.775754,45.632234,63.962368,68.342047,...,28592.983034,141.893726,187.765665,61.535244,87.389620,35.425402,11.236975,67.529357,136702.754440,110.946064,178.542375,153.759820,71.094685,11.243253,0.987571,1.002983,1.039653,75.673764,64.725422,21.427986,0.415242,0.167935,Andromeda II,41.716404,4.340754
3,990025.0,0.887711,72.296275,44701.171827,1.017183,13.418461,12.045101,0.851110,0.854048,104.358165,117.016403,135.064202,34.279137,876.791765,83.156931,58.667575,34.303606,26.860760,307.481700,70.093282,75.687114,86.895446,49.167477,55.694611,112.444875,...,24036.231103,132.538880,114.955851,53.071124,83.295496,29.170003,10.046534,86.083758,94343.188156,95.197475,218.284971,130.235392,78.577601,10.009920,0.965092,0.958244,1.075051,91.209668,82.098925,16.371647,0.510536,0.110758,Andromeda III,20.958750,3.254305
4,990025.0,1.065573,84.289074,52420.899858,1.005840,16.238035,11.407378,0.864309,0.706695,55.235848,117.967371,132.443721,31.020051,1041.230433,96.822014,55.327755,40.442483,26.002740,437.983686,51.769022,78.589342,87.265341,105.854101,46.280471,92.723970,...,36193.877968,153.755894,197.836442,76.417094,81.587402,28.794996,9.109860,73.670355,147270.101607,105.164411,206.324528,169.542658,75.529062,10.523428,1.020507,1.005475,1.041102,73.675667,75.177601,22.295996,0.369113,0.151314,Andromeda IX,5.295678,3.603878

In [4]:
test = pd.read_csv('../eda/outputs/imputed_test_mf.csv')
m, n = test.shape                
print('Data Frame: {} x {}'.format(m,n))                
test.head()

Data Frame: 890 x 79

,galactic year,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",...,"Estimated gross galactic income per capita, male","Estimated gross galactic income per capita, female",Rural population with access to electricity (%),Domestic credit provided by financial sector (% of GGP),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Gross fixed capital formation (% of GGP),"Remittances, inflows (% of GGP)",Population with at least some secondary education (% ages 25 and older),Intergalactic inbound tourists (thousands),"Gross enrolment ratio, primary (% of primary under-age population)","Respiratory disease incidence (per 100,000 people)",Interstellar phone subscriptions (per 100 people),"Interstellar Data Net users, total (% of population)",Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,Gender Inequality Index (GII),galaxy,Private galaxy capital flows (% of GGP),"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total"
0,1007012.0,0.868360,72.982208,19198.499040,0.700413,16.145285,11.113581,0.719579,0.825915,181.824530,76.357958,71.796137,71.977811,819.245976,72.269765,113.394831,75.983899,12.851245,426.589757,59.793499,73.206969,79.051548,80.144699,87.255770,77.624057,...,NaN,NaN,102.306960,NaN,NaN,NaN,75.084941,16.383957,NaN,92046.182973,129.047095,578.672958,70.150003,39.261197,11.067889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Andromeda Galaxy (M31),32.163414,NaN
1,1007012.0,0.772696,73.590698,18345.350181,0.684405,12.167872,7.083681,0.650826,0.505962,193.187549,79.263683,71.723281,37.085742,849.398477,53.465398,139.090298,88.145153,14.152255,496.779346,57.583581,68.021732,74.795340,73.158109,89.776748,124.050371,...,19268.820517,12931.719986,99.189863,77.742674,54.263456,69.496155,38.331603,9.435519,62.266114,92843.780990,131.408452,429.753270,104.910863,34.341097,6.029590,0.673039,0.714560,0.976994,147.451303,164.334975,6.673241,0.687616,Andromeda I,30.668839,5.784397
2,1007012.0,0.941941,81.973436,26708.317145,0.925563,18.175905,13.909442,0.960263,0.937407,74.678611,122.988241,136.685519,34.865297,712.914221,93.116852,59.810528,34.960991,31.242181,435.976780,54.971127,78.814709,87.318457,54.861556,51.049333,72.544281,...,46130.422627,29804.266408,133.499902,112.410524,110.028144,112.483100,29.294321,9.716045,124.671861,98471.178149,117.291927,216.424101,152.699066,89.310138,10.114774,0.975232,0.949269,1.078944,91.321283,80.725039,16.251653,0.467704,Andromeda III,25.648367,3.641324
3,1007012.0,1.079857,89.351427,54738.000742,1.016415,19.927563,12.917355,1.085718,1.010280,65.576254,113.617318,144.223620,27.907457,994.869334,93.992349,50.614834,37.408702,39.063774,452.063178,68.716581,87.959292,90.227666,83.641251,43.621778,61.763540,...,69479.208034,36372.572012,140.513839,212.594379,92.070335,99.724427,27.896438,8.952235,92.240002,157349.220331,111.986697,194.449429,186.126193,81.641747,10.871523,1.041127,1.010276,1.048963,73.708843,76.050073,19.354114,0.344208,Andromeda IX,18.507721,3.467922
4,1007012.0,1.079557,94.084539,54785.657264,1.108535,18.597198,14.490411,1.083277,1.054622,82.576470,116.778787,140.257294,34.620256,667.682672,112.951963,47.121834,32.739008,43.097271,513.265103,76.028442,86.776469,95.761096,79.298329,49.113194,41.016252,...,72697.700583,38990.588810,140.356804,388.073381,115.750229,106.108663,31.155735,7.663965,110.414297,106465.699745,118.241451,183.901921,150.143061,111.458212,12.297071,1.000734,1.059392,1.086341,51.594871,65.860127,21.311365,0.325228,Andromeda V,27.662533,3.691628

In [5]:
import h2o
from h2o.frame import H2OFrame
from h2o.automl import H2OAutoML; h2o.init()
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
  Starting server from C:\Python38\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\devri\AppData\Local\Temp\tmpof_wby3o
  JVM stdout: C:\Users\devri\AppData\Local\Temp\tmpof_wby3o\h2o_devri_started_from_python.out
  JVM stderr: C:\Users\devri\AppData\Local\Temp\tmpof_wby3o\h2o_devri_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Asia/Istanbul
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.0.3
H2O_cluster_version_age:    17 days
H2O_cluster_name:           H2O_from_python_devri_lb0pjx
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    7.101 Gb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.8.0 final
--------------------------  ---------------------------------------------------------

In [6]:
def plot_lgb_history(history):
    for i, key in enumerate(history.evals_result_):
        if i == 0:
            res = pd.DataFrame(history.evals_result_[key])
            res['index'] = np.arange(len(history.evals_result_[key]['l2']))
            res['type'] = key
        temp = pd.DataFrame(history.evals_result_[key])
        temp['type'] = key
        temp['index'] = np.arange(len(history.evals_result_[key]['l2']))
        
        res = res.append(temp, ignore_index=True)
        del temp; gc.collect()
    
    fig = px.scatter(data_frame=res, x='index', y='l2', color='type',
                 title='Learning curve')
    fig.show()

In [8]:
train = pd.get_dummies(train)

In [9]:
scaler = MinMaxScaler()

train_temp = train.drop(['galactic year', 'y'], axis=1)
train_sc = scaler.fit_transform(train_temp)
train_sc = pd.DataFrame(train_sc, columns=train_temp.columns)
del train_temp; gc.collect()

train_sc['galactic year'] = train['galactic year']
train_sc['y'] = train['y']
train_sc

,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",Total unemployment rate (female to male ratio),...,galaxy_Tucana IV,galaxy_UGC 4483,galaxy_UGC 4879 (VV124)[61],galaxy_UGC 7577 (DDO 125),galaxy_UGC 8508 (I Zw 060),galaxy_UGC 8651 (DDO 181),galaxy_UGC 8833,galaxy_UGC 9128 (DDO 187),galaxy_UGC 9240 (DDO 190),galaxy_UGCA 105,galaxy_UGCA 133 (DDO 44),galaxy_UGCA 15 (DDO 6),galaxy_UGCA 276 (DDO 113),galaxy_UGCA 292,galaxy_UGCA 438 (ESO 407-018),galaxy_UGCA 86,galaxy_UGCA 92,galaxy_Ursa Major I Dwarf (UMa I dSph),galaxy_Ursa Major II Dwarf,galaxy_Ursa Minor Dwarf,galaxy_Virgo I,galaxy_Willman 1,"galaxy_Wolf-Lundmark-Melotte (WLM, DDO 221)",galactic year,y
0,0.522168,0.572667,0.122833,0.331835,0.432696,0.487288,0.444684,0.513899,0.604511,0.355213,0.304826,0.995302,0.115232,0.301790,0.341970,0.416847,0.191759,0.102520,0.104587,0.518170,0.478635,0.019736,0.684480,0.291330,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,990025.0,0.049214
1,0.353592,0.427939,0.080683,0.301766,0.197287,0.183211,0.317976,0.331685,0.582724,0.317985,0.342619,0.463287,0.128043,0.189740,0.521479,0.642146,0.279072,0.070815,0.164411,0.455005,0.364563,0.066229,0.776630,0.556247,0.054764,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,990025.0,0.053204
2,0.819898,0.899438,0.231606,0.611006,0.503218,0.661951,0.771523,0.540913,0.200876,0.809917,0.740585,0.512228,0.146877,0.655556,0.098290,0.079772,0.474191,0.084599,0.138280,0.905737,0.738217,0.060943,0.416785,0.196024,0.091968,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,990025.0,0.167935
3,0.647506,0.576846,0.296483,0.677814,0.415386,0.590615,0.602031,0.615118,0.351231,0.812906,0.826055,0.455357,0.127209,0.571556,0.132390,0.109921,0.470866,0.070779,0.139273,0.647872,0.756652,0.065458,0.350949,0.356128,0.042398,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,990025.0,0.110758
4,0.822049,0.758649,0.347539,0.667213,0.537149,0.553386,0.615792,0.478649,0.168526,0.822122,0.808662,0.408678,0.147376,0.696777,0.123356,0.141288,0.452960,0.093942,0.112052,0.699343,0.762742,0.137849,0.275985,0.284537,0.076420,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,990025.0,0.151314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3860,0.878492,0.682822,0.229769,0.643321,0.638261,0.443538,0.654351,0.681976,0.410938,0.823116,0.774655,0.340826,0.156033,0.721017,0.138433,0.129135,0.325884,0.121540,0.169693,0.714671,0.777735,0.130579,0.284805,0.427167,0.064223,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1015056.0,0.040206
3861,0.881401,0.867625,0.435427,0.731503,0.987159,0.797177,0.826763,0.825101,0.226979,0.773315,0.864817,0.497782,0.138997,0.708923,0.182002,0.146428,0.592741,0.139824,0.098554,0.873251,0.840126,0.044341,0.327026,0.041884,0.046212,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1015056.0,0.204002
3862,0.770605,0.739523,0.664641,0.841479,0.638707,0.654046,0.703773,0.722724,0.268501,0.822979,0.747764,0.644510,0.143431,0.841757,0.039485,0.038917,0.225342,0.097200,0.112905,0.797511,0.695393,0.077845,0.395077,0.254310,0.078923,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1015056.0,0.028505
3863,0.383311,0.354261,0.178877,0.205526,0.241411,0.165924,0.155471,0.305690,0.910320,0.373953,0.313953,0.404556,0.094053,0.306523,0.508072,0.527646,0.104297,0.069237,0.121267,0.347156,0.314045,0.106156,0.751015,0.728730,0.042548,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1015056.0,0.018371
3864,0.768066,0.883351,0.410170,0.866856,0.613939,0.669474,0.778679,0.630941,0.333968,0.836404,0.756877,0.521570,0.074935,0.719976,0.137403,0.163632,0.041233,0.129809,0.104736,0.749748,0.820950,0.109451,0.217547,0.208196,0.335129,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1015056.0,0.034701

In [10]:
train.rename(columns={
    "Population, ages 15â€“64 (millions)": "pop_age_15_64_mil",
    "Unemployment, youth (% ages 15â€“24)": "unemp_youth_perc_ages_15_24",
    "galaxy_BoÃ¶tes I": "galaxy_Bootes_i",
    "galaxy_BoÃ¶tes II": "galaxy_Bootes_ii",
    "galaxy_BoÃ¶tes III": "galaxy_Bootes_iii",
    "galaxy_BoÃ¶tes IV": "galaxy_Bootes_iv"
}, inplace=True)

In [11]:
last_n_years = 3
val_year = train['galactic year'].unique()[-last_n_years]
train_set = train[train['galactic year']<val_year]
val_set = train[train['galactic year']>=val_year]

In [12]:
y = 'y'
X = train_set.columns.drop(y).tolist()

In [13]:
train_set = H2OFrame(train_set)
val_set = H2OFrame(val_set)

y_train = train_set[y].as_data_frame().values
y_val = val_set[y].as_data_frame().values

# No need for eval set

Parse progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%
Parse progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%

**Examples**

    >>> import h2o
    >>> from h2o.automl import H2OAutoML
    >>> h2o.init()
    >>> # Import a sample binary outcome train/test set into H2O
    >>> train = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
    >>> test = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_test_5k.csv")
    >>> # Identify the response and set of predictors
    >>> y = "response"
    >>> x = list(train.columns)  #if x is defined as all columns except the response, then x is not required
    >>> x.remove(y)
    >>> # For binary classification, response should be a factor
    >>> train[y] = train[y].asfactor()
    >>> test[y] = test[y].asfactor()
    >>> # Run AutoML for 30 seconds
    >>> aml = H2OAutoML(max_runtime_secs = 30)
    >>> aml.train(x = x, y = y, training_frame = train)
    >>> # Print Leaderboard (ranked by xval metrics)
    >>> aml.leaderboard
    >>> # (Optional) Evaluate performance on a test set
    >>> perf = aml.leader.model_performance(test)
    >>> perf.auc()

In [19]:
# num_leaves << 2^(max_depth)

aml = H2OAutoML(
    nfolds=0, # if nfolds != 0, then validation_frame in train() is ignored.
    balance_classes=False,
    class_sampling_factors=None,
    max_after_balance_size=5.0,
    max_runtime_secs=300,
    max_runtime_secs_per_model=None,
    max_models=None,
    stopping_metric='AUTO',
    stopping_tolerance=None,
    stopping_rounds=3,
    seed=None,
    project_name=None,
    exclude_algos=None,
    include_algos=None,
    exploitation_ratio=0,
    modeling_plan=None,
    monotone_constraints=None,
    algo_parameters=None,
    keep_cross_validation_predictions=False,
    keep_cross_validation_models=False,
    keep_cross_validation_fold_assignment=False,
    sort_metric='RMSE',
    export_checkpoints_dir=None,
    verbosity='warn'
)

aml.train(x=X, y=y,
                training_frame=train_set,
                validation_frame=val_set
    )

y_pred_train = aml.predict(train_set[X]).as_data_frame().values
y_pred_val = aml.predict(val_set[X]).as_data_frame().values

train_rmse = mean_squared_error(y_true=y_train, y_pred=y_pred_train, squared=False)
val_rmse = mean_squared_error(y_true=y_val, y_pred=y_pred_val, squared=False)
print('#'*60)
print(f'RMSE Train: {train_rmse: .8f}')
print(f'RMSE Valid: {val_rmse: .8f}\tRatio (val/train): {val_rmse/train_rmse: .5f}')

AutoML progress: |
03:54:59.584: AutoML: XGBoost is not available; skipping it.

â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%
gbm prediction progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%
gbm prediction progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%
############################################################
RMSE Train:  0.00204323
RMSE Valid:  0.04964738	Ratio (val/train):  24.29851

In [20]:
aml.leaderboard

model_id,rmse,mean_residual_deviance,mse,mae,rmsle
GBM_grid__1_AutoML_20200531_035459_model_109,0.00668254,4.46563e-05,4.46563e-05,0.00255124,0.00574197
GBM_grid__1_AutoML_20200531_035459_model_77,0.00695638,4.83912e-05,4.83912e-05,0.0029634,0.00599088
GBM_grid__1_AutoML_20200531_035459_model_53,0.00699902,4.89864e-05,4.89864e-05,0.00273083,0.00600659
GBM_grid__1_AutoML_20200531_035459_model_26,0.00739403,5.46717e-05,5.46717e-05,0.0027407,0.00627279
GBM_grid__1_AutoML_20200531_035459_model_15,0.0077246,5.96694e-05,5.96694e-05,0.00371612,0.00663451
GBM_grid__1_AutoML_20200531_035459_model_57,0.00772802,5.97223e-05,5.97223e-05,0.00278505,0.00653473
GBM_3_AutoML_20200531_035459,0.00784675,6.15715e-05,6.15715e-05,0.00324831,0.00671024
GBM_grid__1_AutoML_20200531_035459_model_28,0.00788707,6.22059e-05,6.22059e-05,0.00307446,0.00674125
GBM_grid__1_AutoML_20200531_035459_model_68,0.00789942,6.24008e-05,6.24008e-05,0.00297537,0.00672544
GBM_2_AutoML_20200531_035459,0.00801172,6.41876e-05,6.41876e-05,0.00348603,0.00687828

In [21]:
# plot_history(lgbm)

In [17]:
test = pd.get_dummies(test)

In [18]:
galaxies_unseen_test = ['galaxy_Andromeda XIX[60]', 'galaxy_NGC 5253', 'galaxy_Tucana Dwarf',
       'galaxy_Andromeda XXIV', 'Population..ages.15a..64..millions.', 'galaxy_Hercules Dwarf',
       'Unemployment..youth....ages.15a..24.', 'galaxy_Andromeda XXII[57]', 'galaxy_Andromeda XVIII[60]',
       'galaxy_Triangulum Galaxy (M33)', 'galaxy_Andromeda XII']

for galaxy in galaxies_unseen_test:
    test[galaxy] = 0
    
X_test = test[X].to_numpy()

KeyError: "['galaxy_Bootes_iii', 'galaxy_Bootes_ii', 'pop_age_15_64_mil', 'galaxy_Bootes_i', 'unemp_youth_perc_ages_15_24', 'galaxy_Bootes_iv'] not in index"

In [ ]:
y_pred_test = lgbm.predict(X_test)

In [ ]:
pred_output = pd.DataFrame()
pred_output['y_pred'] = y_pred_test
pred_output.reset_index(inplace=True)
pred_output.rename(columns = {
    "index": "Index"
    }, inplace=True)
pred_output

In [ ]:
# os.makedirs('./outputs', exist_ok=True)
# pred_output.to_csv('./outputs/y_pred_lgbm_mf_0525val.csv', index=False)

In [ ]:
print("Train samples:", y_pred_train.shape[0])
print("Validation samples:", y_pred_val.shape[0])
print("Test samples:", y_pred_test.shape[0])

In [ ]:
px.histogram(pd.DataFrame(y_pred_train), x=0)

In [ ]:
px.histogram(pd.DataFrame(y_pred_val), x=0)

In [ ]:
px.histogram(pd.DataFrame(y_pred_test), x=0)