In [1]:
# Scientific libraries		              
import numpy as np		              
import scipy as sp		              
import pandas as pd		              
import json		              
import missingno as msno		              

# Loading Plotting Modules		              
import matplotlib		              
import matplotlib.pyplot as plt		              
import seaborn as sns		              
%matplotlib inline		              
import chart_studio.plotly as py		              
import plotly.figure_factory as ff		              
import plotly.graph_objects as go		              
import plotly.express as px		              
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot		              
init_notebook_mode(connected=True)		              
		              
import os		              
import gc

In [2]:
# Setting Data Frame Options                      
pd.set_option('display.max_rows', 40)                      
pd.set_option('display.max_columns', 50)                      
pd.set_option('display.width', 100)                      
pd.set_option('display.max_colwidth', 100)                      

# Setting Plot Configuration                      
sns.set(rc={'figure.figsize':(19,11)}, style = 'white')

In [3]:
train = pd.read_csv('./outputs/imputed_train_mfc2.csv')                
m_train, n_train = train.shape                
print('Data Frame: {} x {}'.format(m_train,n_train))                
train.head()

Data Frame: 3865 x 80

,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",Total unemployment rate (female to male ratio),...,Rural population with access to electricity (%),Domestic credit provided by financial sector (% of GGP),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Gross fixed capital formation (% of GGP),"Remittances, inflows (% of GGP)",Population with at least some secondary education (% ages 25 and older),Intergalactic inbound tourists (thousands),"Gross enrolment ratio, primary (% of primary under-age population)","Respiratory disease incidence (per 100,000 people)",Interstellar phone subscriptions (per 100 people),"Interstellar Data Net users, total (% of population)",Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),galactic year,galaxy,y
0,0.628657,63.125200,27109.234310,0.646039,8.240543,8.056301,0.604385,0.554281,167.574333,69.858560,52.372335,38.305483,681.841086,22.131436,150.259290,129.841789,12.403812,490.446400,60.121580,57.028183,69.825369,46.018230,98.216072,174.617899,2.489476,...,42.259215,75.604799,40.340192,51.365222,42.616284,9.172756,43.161188,100883.108408,89.310781,456.952497,70.195481,30.805295,6.962975,0.522379,0.608718,0.908864,142.993886,144.076302,18.634486,6.234301,27.702823,0.863048,990025,Large Magellanic Cloud (LMC),0.052590
1,0.818082,81.004994,30166.793958,0.852246,10.671823,4.742470,0.833624,0.467873,152.522198,96.561069,100.189685,36.255559,423.973089,89.294181,117.069332,61.822590,13.054898,560.547706,58.573002,69.873905,76.752305,40.167960,88.322574,109.892385,2.716217,...,109.529704,57.214150,57.314932,56.187355,29.908422,6.225946,44.780023,102317.431056,120.886080,326.354863,77.060535,34.872320,7.114982,0.722689,0.791613,0.910816,145.477446,136.493478,19.177926,4.348810,22.785018,0.750002,990025,Camelopardalis B,0.059868
2,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,209.813266,61.928785,46.330758,18.093991,285.572207,57.491083,226.523760,134.558437,15.963001,555.012461,43.078497,59.462626,59.152506,91.093668,114.163995,230.573666,2.319564,...,38.617579,76.141735,42.405827,53.927715,18.732049,4.138115,24.030945,92511.563102,96.626831,421.483076,53.907086,29.114330,7.733610,0.459603,0.525987,0.872373,189.262879,193.850529,21.151265,6.534020,26.768739,0.892916,990025,Virgo I,0.050449
3,0.555862,52.333293,20124.465186,0.610815,8.493268,7.724112,0.481901,0.537697,174.839118,66.311481,48.357601,30.697025,327.202247,47.785456,279.000175,193.228799,12.940991,766.807703,51.318372,50.535797,54.931369,92.727892,97.645232,198.971328,2.424140,...,41.333327,79.863066,39.402206,53.989065,29.084256,9.742580,43.405245,96236.061427,83.523248,462.346690,51.139822,28.982966,14.359786,0.432888,0.542178,0.873981,138.678368,145.831901,16.611053,5.912194,27.011577,0.878899,990025,UGC 8651 (DDO 181),0.049394
4,0.991196,81.802464,81033.956906,1.131163,13.800672,13.188907,0.910341,0.918353,71.885345,116.316132,128.264301,34.497468,633.799718,103.562629,28.359587,51.098250,25.521926,585.434804,56.158054,85.020965,84.708158,71.493810,53.835875,61.008654,2.633213,...,134.967049,161.034224,77.223935,75.475076,31.398393,10.046752,66.674651,96375.765399,115.106632,192.750355,168.574611,86.305441,10.164208,0.984117,0.981311,1.055133,66.627461,72.171514,35.346902,5.611753,26.549992,0.410660,990025,Tucana Dwarf,0.154247

In [4]:
test = pd.read_csv('./outputs/imputed_test_mfc2.csv')                
m_test, n_test = test.shape                
print('Data Frame: {} x {}'.format(m_test,n_test))                
test.head()

Data Frame: 890 x 79

,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",Total unemployment rate (female to male ratio),...,"Estimated gross galactic income per capita, female",Rural population with access to electricity (%),Domestic credit provided by financial sector (% of GGP),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Gross fixed capital formation (% of GGP),"Remittances, inflows (% of GGP)",Population with at least some secondary education (% ages 25 and older),Intergalactic inbound tourists (thousands),"Gross enrolment ratio, primary (% of primary under-age population)","Respiratory disease incidence (per 100,000 people)",Interstellar phone subscriptions (per 100 people),"Interstellar Data Net users, total (% of population)",Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),galactic year,galaxy
0,0.456086,51.562543,12236.576447,0.593325,10.414164,10.699072,0.547114,0.556267,232.621842,105.193088,64.241392,17.418350,709.974500,73.297380,146.341817,100.005259,12.562363,489.982611,53.149371,56.249570,60.594004,82.932522,106.521709,169.754218,2.509936,...,13681.345449,65.920807,96.448861,59.897899,70.066364,16.631279,11.064357,62.046027,99833.452672,104.199637,398.486742,87.291073,33.699239,7.830928,0.578841,0.648238,0.937948,187.932285,190.203266,12.229105,7.611505,24.146867,0.834866,1007012,KK98 77
1,0.529835,57.228262,3431.883825,0.675407,7.239485,5.311122,0.497688,0.409969,247.580771,55.730638,46.217440,33.027886,663.067688,52.484030,166.038771,108.221474,13.200530,514.865394,54.980664,56.843449,60.719106,73.546787,113.037027,183.668653,2.449988,...,13112.402114,40.524312,81.914200,35.913800,39.242603,29.799164,9.411752,38.035978,98273.087328,79.498161,352.781610,63.668477,31.235817,7.493285,0.465698,0.564255,0.882829,191.034292,199.069702,18.083477,6.588888,24.547531,0.880047,1007012,Reticulum III
2,0.560976,59.379539,27562.914252,0.594624,11.774890,5.937797,0.544744,0.486167,249.798771,58.755900,48.897493,31.613362,679.824897,52.027110,154.631808,100.317484,13.144451,518.007633,55.026892,60.597547,61.235156,76.754857,113.361712,178.938322,2.437677,...,13935.601262,39.724189,82.407018,37.618966,47.066875,29.734731,9.571031,43.073675,96229.282018,113.616580,338.213199,69.731913,31.865079,7.822061,0.539204,0.589167,0.939487,187.440453,193.334980,16.383094,7.047281,25.892463,0.832374,1008016,Reticulum III
3,0.565910,59.952390,20352.232905,0.837700,11.613621,10.067882,0.691641,0.523441,211.505060,70.176431,61.254104,34.399007,703.504462,66.914935,138.682272,85.920319,12.103836,466.974474,52.122883,60.790951,62.620380,78.296895,105.044190,155.484047,2.629991,...,16989.037384,56.099340,81.731894,56.748633,61.864548,32.176466,9.072665,56.951917,98961.843177,115.107183,430.777822,86.627405,33.752004,7.387747,0.670267,0.658327,0.968023,181.052146,182.930386,21.110558,7.587255,26.275656,0.805579,1007012,Segue 1
4,0.588274,55.428320,23959.704016,0.520579,10.392416,6.374637,0.530676,0.580418,234.721069,69.768692,51.316940,15.657091,1106.554194,64.382217,219.588961,129.974418,14.013421,474.877713,21.305665,59.144562,63.990109,80.409057,111.084652,162.451451,2.421466,...,18103.974021,50.233592,86.296925,29.065459,58.562225,13.313253,10.716067,42.980727,99276.256730,92.080977,458.186555,79.177012,41.585873,7.357729,0.583373,0.600445,0.856158,206.674424,224.104054,8.630927,7.687626,25.907442,0.891128,1013042,Virgo I

In [5]:
df = train.append(test, ignore_index=True)
df

,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",Total unemployment rate (female to male ratio),...,Rural population with access to electricity (%),Domestic credit provided by financial sector (% of GGP),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Gross fixed capital formation (% of GGP),"Remittances, inflows (% of GGP)",Population with at least some secondary education (% ages 25 and older),Intergalactic inbound tourists (thousands),"Gross enrolment ratio, primary (% of primary under-age population)","Respiratory disease incidence (per 100,000 people)",Interstellar phone subscriptions (per 100 people),"Interstellar Data Net users, total (% of population)",Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),galactic year,galaxy,y
0,0.628657,63.125200,27109.234310,0.646039,8.240543,8.056301,0.604385,0.554281,167.574333,69.858560,52.372335,38.305483,681.841086,22.131436,150.259290,129.841789,12.403812,490.446400,60.121580,57.028183,69.825369,46.018230,98.216072,174.617899,2.489476,...,42.259215,75.604799,40.340192,51.365222,42.616284,9.172756,43.161188,100883.108408,89.310781,456.952497,70.195481,30.805295,6.962975,0.522379,0.608718,0.908864,142.993886,144.076302,18.634486,6.234301,27.702823,0.863048,990025,Large Magellanic Cloud (LMC),0.052590
1,0.818082,81.004994,30166.793958,0.852246,10.671823,4.742470,0.833624,0.467873,152.522198,96.561069,100.189685,36.255559,423.973089,89.294181,117.069332,61.822590,13.054898,560.547706,58.573002,69.873905,76.752305,40.167960,88.322574,109.892385,2.716217,...,109.529704,57.214150,57.314932,56.187355,29.908422,6.225946,44.780023,102317.431056,120.886080,326.354863,77.060535,34.872320,7.114982,0.722689,0.791613,0.910816,145.477446,136.493478,19.177926,4.348810,22.785018,0.750002,990025,Camelopardalis B,0.059868
2,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,209.813266,61.928785,46.330758,18.093991,285.572207,57.491083,226.523760,134.558437,15.963001,555.012461,43.078497,59.462626,59.152506,91.093668,114.163995,230.573666,2.319564,...,38.617579,76.141735,42.405827,53.927715,18.732049,4.138115,24.030945,92511.563102,96.626831,421.483076,53.907086,29.114330,7.733610,0.459603,0.525987,0.872373,189.262879,193.850529,21.151265,6.534020,26.768739,0.892916,990025,Virgo I,0.050449
3,0.555862,52.333293,20124.465186,0.610815,8.493268,7.724112,0.481901,0.537697,174.839118,66.311481,48.357601,30.697025,327.202247,47.785456,279.000175,193.228799,12.940991,766.807703,51.318372,50.535797,54.931369,92.727892,97.645232,198.971328,2.424140,...,41.333327,79.863066,39.402206,53.989065,29.084256,9.742580,43.405245,96236.061427,83.523248,462.346690,51.139822,28.982966,14.359786,0.432888,0.542178,0.873981,138.678368,145.831901,16.611053,5.912194,27.011577,0.878899,990025,UGC 8651 (DDO 181),0.049394
4,0.991196,81.802464,81033.956906,1.131163,13.800672,13.188907,0.910341,0.918353,71.885345,116.316132,128.264301,34.497468,633.799718,103.562629,28.359587,51.098250,25.521926,585.434804,56.158054,85.020965,84.708158,71.493810,53.835875,61.008654,2.633213,...,134.967049,161.034224,77.223935,75.475076,31.398393,10.046752,66.674651,96375.765399,115.106632,192.750355,168.574611,86.305441,10.164208,0.984117,0.981311,1.055133,66.627461,72.171514,35.346902,5.611753,26.549992,0.410660,990025,Tucana Dwarf,0.154247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4750,0.898146,82.394205,26036.114874,0.774076,14.296358,11.914942,0.839772,0.768569,122.765169,109.685473,108.260917,37.037824,799.384692,78.835231,73.145690,52.644179,16.444409,484.979360,55.310975,77.446091,82.745318,77.027569,78.867640,118.676791,2.696994,...,122.581478,102.299039,75.518299,76.670125,33.006532,11.966842,75.514517,100931.131526,123.948074,224.453281,111.711007,47.946743,7.663565,0.824444,0.841598,1.043943,117.645294,117.367034,28.467002,4.643949,23.940795,0.667214,1016064,ESO 383-087 (ISG 39),NaN
4751,0.898146,82.394205,26036.114874,0.774076,14.296358,11.914942,0.839772,0.768569,122.765169,109.685473,108.260917,37.037824,799.384692,78.835231,73.145690,52.644179,16.444409,484.979360,55.310975,77.446091,82.745318,77.027569,78.867640,118.676791,2.696994,...,122.581478,102.299039,75.518299,76.670125,33.006532,11.966842,75.514517,100931.131526,123.948074,224.453281,111.711007,47.946743,7.663565,0.824444,0.841598,1.043943,117.645294,117.367034,28.467002,4.643949,23.940795,0.667214,1016064,NGC 247,NaN
4752,0.898146,82.394205,26036.114874,0.774076,14.296358,11.914942,0.839772,0.768569,122.765169,109.685473,108.260917,37.037824,799.384692,78.835231,73.145690,52.644179,16.444409,484.979360,55.310975,77.446091,82.745318,77.027569,78.867640,118.676791,2.696994,...,122.581478,102.299039,75.518299,76.670125,33.006532,11.966842,75.514517,100931.131526,123.948074,224.453281,111.711007,47.946743,7.663565,0.824444,0.841598,1.043943,117.645294,117.367034,28.467002,4.643949,23.940795,0.667214,1016064,ESO 325-11,NaN
4753,0.898146,82.394205,26036.114874,0.774076,14.296358,11.914942,0.839772,0.768569,122.765169,109.685473,108.260917,37.037824,799.384692,78.835231,73.145690,52.644179,16.444409,484.979360,55.310975,77.446091,82.745318,77.027569,78.867640,118.676791,2.696994,...,122.581478,102.299039,75.518299,76.670125,33.006532,11.966842,75.514517,100931.131526,123.948074,224.453281,111.711007,47.946743,7.663565,0.824444,0.841598,1.043943,117.645294,117.367034,28.467002,4.643949,23.940795,0.667214,1016064,ESO 540-032,NaN
4754,0.898146,82.394205,26036.114874,0.774076,14.296358,11.914942,0.839772,0.768569,122.765169,109.685473,108.260917,37.037824,799.384692,78.835231,73.145690,52.644179,16.444409,484.979360,55.310975,77.446091,82.745318,77.027569,78.867640,118.676791,2.696994,...,122.581478,102.299039,75.518299,76.670125,33.006532,11.966842,75.514517,100931.131526,123.948074,224.453281,111.711007,47.946743,7.663565,0.824444,0.841598,1.043943,117.645294,117.367034,28.467002,4.643949,23.940795,0.667214,1016064,KK98 77,NaN

In [6]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler

In [7]:
df_scaled = df.drop(['galactic year', 'galaxy', 'y'], axis=1)
cols = df_scaled.columns

In [8]:
scaler = StandardScaler()
# scaler = MinMaxScaler()
# scaler = MaxAbsScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_scaled), columns=cols)
df_scaled

,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",Total unemployment rate (female to male ratio),...,Renewable energy consumption (% of total final energy consumption),"Estimated gross galactic income per capita, male","Estimated gross galactic income per capita, female",Rural population with access to electricity (%),Domestic credit provided by financial sector (% of GGP),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Gross fixed capital formation (% of GGP),"Remittances, inflows (% of GGP)",Population with at least some secondary education (% ages 25 and older),Intergalactic inbound tourists (thousands),"Gross enrolment ratio, primary (% of primary under-age population)","Respiratory disease incidence (per 100,000 people)",Interstellar phone subscriptions (per 100 people),"Interstellar Data Net users, total (% of population)",Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII)
0,-1.596385,-1.387531,-0.259141,-0.958869,-1.874066,-0.730853,-1.156238,-0.995341,0.559709,-1.609004,-1.469468,0.867516,-0.241094,-2.933265,1.367641,2.523176,-0.921325,-0.096066,0.050196,-2.016518,-1.071139,-0.700463,0.886947,1.443292,-0.214593,...,2.045439,-0.665033,-0.783351,-1.644535,-0.866187,-1.315820,-1.099710,2.135268,-0.376724,-1.299259,-0.077327,-1.851509,1.310202,-1.131566,-1.043454,-0.783809,-1.588038,-1.452340,-1.409257,0.445623,0.445992,-0.373666,0.301773,0.243022,1.251509
1,-0.403092,0.351834,-0.095928,0.112484,-1.191399,-1.748615,0.163272,-1.434446,0.270193,-0.225282,0.057065,0.561944,-0.755942,0.496888,0.588356,-0.024708,-0.808862,0.122492,0.006960,-0.548136,-0.352312,-0.818048,0.433192,-0.156238,0.024232,...,-0.335783,-0.371023,-0.499773,0.150650,-1.287332,-0.644594,-0.891800,-0.072697,-0.939707,-1.232742,-0.053963,0.330062,0.281701,-0.970504,-0.882857,-0.697497,-0.434850,-0.199583,-1.382259,0.507914,0.256863,-0.318553,-0.408867,-0.063289,0.593982
2,-1.402445,-1.733333,-1.255619,-1.718860,-1.705659,-1.490168,-1.934886,-1.963129,1.372140,-2.019924,-1.662341,-2.145309,-1.032268,-1.127368,3.158295,2.699853,-0.306538,0.105234,-0.425634,-1.738239,-2.178691,0.205518,1.618380,2.826099,-0.393560,...,2.326302,-0.787285,-0.866863,-1.741716,-0.853891,-1.234140,-0.989226,-2.014570,-1.338584,-2.085314,-0.213697,-1.346035,1.030868,-1.513712,-1.110227,-0.346230,-1.949438,-2.019017,-1.913757,1.606116,1.687450,-0.118425,0.414737,0.184842,1.425234
3,-2.054962,-2.437379,-0.631990,-1.141876,-1.803105,-0.832877,-1.861258,-1.079620,0.699441,-1.792813,-1.597636,-0.266638,-0.949151,-1.623057,4.390417,4.897545,-0.828537,0.765557,-0.195583,-2.758656,-2.616730,0.238365,0.860766,2.045126,-0.283411,...,1.953451,-0.739543,-0.984976,-1.669243,-0.768673,-1.352911,-0.986581,-0.215894,-0.267860,-1.289231,-0.153026,-2.251376,1.352683,-1.578635,-1.115414,3.416211,-2.103235,-1.908113,-1.891523,0.337384,0.489780,-0.578875,0.180371,0.199967,1.343704
4,0.687448,0.429412,2.619377,1.561600,-0.312865,0.845499,0.604860,0.854778,-1.280791,0.798423,0.953327,0.299874,-0.337011,1.225609,-1.494507,-0.426423,1.344598,0.200083,-0.060463,1.183309,0.473289,-0.188424,-1.148501,-1.364278,-0.063195,...,-0.871853,2.738145,3.013200,0.829472,1.090143,0.142661,-0.060195,0.186182,-0.209749,-0.333100,-0.150750,-0.069246,-0.770481,1.176528,1.148121,1.033899,1.070191,1.099775,0.612991,-1.469757,-1.347443,1.321241,0.067135,0.171217,-1.379787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4750,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,-0.411833,-0.450031,-0.494473,0.498950,-0.254890,0.075215,-0.008670,0.465593,0.157081,0.030126,-0.076545,0.541618,-0.520809,-0.157561,-0.366577,-0.386003,0.150956,0.142792,0.458285,-0.190156,-0.220185,0.623509,-0.297630,0.008700,0.112447
4751,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,-0.411833,-0.450031,-0.494473,0.498950,-0.254890,0.075215,-0.008670,0.465593,0.157081,0.030126,-0.076545,0.541618,-0.520809,-0.157561,-0.366577,-0.386003,0.150956,0.142792,0.458285,-0.190156,-0.220185,0.623509,-0.297630,0.008700,0.112447
4752,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,-0.411833,-0.450031,-0.494473,0.498950,-0.254890,0.075215,-0.008670,0.465593,0.157081,0.030126,-0.076545,0.541618,-0.520809,-0.157561,-0.366577,-0.386003,0.150956,0.142792,0.458285,-0.190156,-0.220185,0.623509,-0.297630,0.008700,0.112447
4753,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,-0.411833,-0.450031,-0.494473,0.498950,-0.254890,0.075215,-0.008670,0.465593,0.157081,0.030126,-0.076545,0.541618,-0.520809,-0.157561,-0.366577,-0.386003,0.150956,0.142792,0.458285,-0.190156,-0.220185,0.623509,-0.297630,0.008700,0.112447
4754,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,-0.411833,-0.450031,-0.494473,0.498950,-0.254890,0.075215,-0.008670,0.465593,0.157081,0.030126,-0.076545,0.541618,-0.520809,-0.157561,-0.366577,-0.386003,0.150956,0.142792,0.458285,-0.190156,-0.220185,0.623509,-0.297630,0.008700,0.112447

In [9]:
df_scaled['galaxy'] = df['galaxy']
df_scaled = pd.get_dummies(df_scaled, columns=['galaxy'])
df_scaled

,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,"Intergalactic Development Index (IDI), Rank",Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Gross capital formation (% of GGP),"Population, total (millions)","Population, urban (%)","Mortality rate, under-five (per 1,000 live births)","Mortality rate, infant (per 1,000 live births)",Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),"Population, ages 15â€“64 (millions)","Population, ages 65 and older (millions)","Life expectancy at birth, male (galactic years)","Life expectancy at birth, female (galactic years)","Population, under age 5 (millions)",Young age (0-14) dependency ratio (per 100 creatures ages 15-64),"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",Total unemployment rate (female to male ratio),...,galaxy_Tucana II,galaxy_Tucana III,galaxy_Tucana IV,galaxy_UGC 4483,galaxy_UGC 4879 (VV124)[61],galaxy_UGC 7577 (DDO 125),galaxy_UGC 8508 (I Zw 060),galaxy_UGC 8651 (DDO 181),galaxy_UGC 8833,galaxy_UGC 9128 (DDO 187),galaxy_UGC 9240 (DDO 190),galaxy_UGCA 105,galaxy_UGCA 133 (DDO 44),galaxy_UGCA 15 (DDO 6),galaxy_UGCA 276 (DDO 113),galaxy_UGCA 292,galaxy_UGCA 438 (ESO 407-018),galaxy_UGCA 86,galaxy_UGCA 92,galaxy_Ursa Major I Dwarf (UMa I dSph),galaxy_Ursa Major II Dwarf,galaxy_Ursa Minor Dwarf,galaxy_Virgo I,galaxy_Willman 1,"galaxy_Wolf-Lundmark-Melotte (WLM, DDO 221)"
0,-1.596385,-1.387531,-0.259141,-0.958869,-1.874066,-0.730853,-1.156238,-0.995341,0.559709,-1.609004,-1.469468,0.867516,-0.241094,-2.933265,1.367641,2.523176,-0.921325,-0.096066,0.050196,-2.016518,-1.071139,-0.700463,0.886947,1.443292,-0.214593,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,-0.403092,0.351834,-0.095928,0.112484,-1.191399,-1.748615,0.163272,-1.434446,0.270193,-0.225282,0.057065,0.561944,-0.755942,0.496888,0.588356,-0.024708,-0.808862,0.122492,0.006960,-0.548136,-0.352312,-0.818048,0.433192,-0.156238,0.024232,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,-1.402445,-1.733333,-1.255619,-1.718860,-1.705659,-1.490168,-1.934886,-1.963129,1.372140,-2.019924,-1.662341,-2.145309,-1.032268,-1.127368,3.158295,2.699853,-0.306538,0.105234,-0.425634,-1.738239,-2.178691,0.205518,1.618380,2.826099,-0.393560,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,-2.054962,-2.437379,-0.631990,-1.141876,-1.803105,-0.832877,-1.861258,-1.079620,0.699441,-1.792813,-1.597636,-0.266638,-0.949151,-1.623057,4.390417,4.897545,-0.828537,0.765557,-0.195583,-2.758656,-2.616730,0.238365,0.860766,2.045126,-0.283411,...,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0.687448,0.429412,2.619377,1.561600,-0.312865,0.845499,0.604860,0.854778,-1.280791,0.798423,0.953327,0.299874,-0.337011,1.225609,-1.494507,-0.426423,1.344598,0.200083,-0.060463,1.183309,0.473289,-0.188424,-1.148501,-1.364278,-0.063195,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4750,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4751,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4752,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4753,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4754,0.101275,0.486978,-0.316425,-0.293653,-0.173683,0.454232,0.198664,0.093615,-0.302159,0.454823,0.314733,0.678552,-0.006411,-0.037275,-0.442951,-0.368515,-0.223384,-0.113111,-0.084113,0.317433,0.269600,-0.077199,-0.000447,0.060846,0.003985,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [10]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

In [11]:
ncol = df_scaled.shape[1]
encoding_dim = 50

In [12]:
input_dim = Input(shape = (ncol, ))

# Encoder Layers
encoded1 = Dense(200, activation = 'relu')(input_dim)
encoded2 = Dense(100, activation = 'relu')(encoded1)
encoded3 = Dense(75, activation = 'relu')(encoded2)
encoded4 = Dense(encoding_dim, activation = 'relu')(encoded3)

# Decoder Layers
decoded1 = Dense(75, activation = 'relu')(encoded4)
decoded2 = Dense(100, activation = 'relu')(decoded1)
decoded3 = Dense(200, activation = 'relu')(decoded2)
decoded5 = Dense(ncol, activation = 'sigmoid')(decoded3)

# Combine Encoder and Deocder layers
autoencoder = Model(inputs = input_dim, outputs = decoded5)

# Compile the Model
autoencoder.compile(optimizer = 'adadelta', loss = 'binary_crossentropy')
autoencoder.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 258)]             0
_________________________________________________________________
dense (Dense)                (None, 200)               51800
_________________________________________________________________
dense_1 (Dense)              (None, 100)               20100
_________________________________________________________________
dense_2 (Dense)              (None, 75)                7575
_________________________________________________________________
dense_3 (Dense)              (None, 50)                3800
_________________________________________________________________
dense_4 (Dense)              (None, 75)                3825
_________________________________________________________________
dense_5 (Dense)              (None, 100)               7600
_________________________________________________________________
dense_6 (Dense)              (None, 200)               20200
_________________________________________________________________
dense_7 (Dense)              (None, 258)               51858
=================================================================
Total params: 166,758
Trainable params: 166,758
Non-trainable params: 0
_________________________________________________________________

In [13]:
X_train = df_scaled.to_numpy()

In [14]:
history = autoencoder.fit(X_train, X_train, epochs = 20, batch_size = 32, shuffle = False, validation_data = (X_train, X_train))

Epoch 1/20
149/149 [==============================] - 0s 3ms/step - loss: 0.6948 - val_loss: 0.6947
Epoch 2/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6946 - val_loss: 0.6944
Epoch 3/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6943 - val_loss: 0.6942
Epoch 4/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6940 - val_loss: 0.6939
Epoch 5/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6938 - val_loss: 0.6936
Epoch 6/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6935 - val_loss: 0.6933
Epoch 7/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6932 - val_loss: 0.6931
Epoch 8/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6929 - val_loss: 0.6928
Epoch 9/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6926 - val_loss: 0.6925
Epoch 10/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6924 - val_loss: 0.6922
Epoch 11/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6921 - val_loss: 0.6919
Epoch 12/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6918 - val_loss: 0.6917
Epoch 13/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6915 - val_loss: 0.6914
Epoch 14/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6913 - val_loss: 0.6911
Epoch 15/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6910 - val_loss: 0.6908
Epoch 16/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6907 - val_loss: 0.6906
Epoch 17/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6904 - val_loss: 0.6903
Epoch 18/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6902 - val_loss: 0.6900
Epoch 19/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6899 - val_loss: 0.6898
Epoch 20/20
149/149 [==============================] - 0s 2ms/step - loss: 0.6896 - val_loss: 0.6895

In [15]:
encoder = Model(inputs = input_dim, outputs = encoded4)
encoded_input = Input(shape = (encoding_dim, ))

In [16]:
encoded_df = pd.DataFrame(encoder.predict(X_train))
encoded_df = encoded_df.add_prefix('feature_')
encoded_df.head(m_train+m_test-5)

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49
0,0.239396,0.133525,0.000000,0.125884,0.000000,0.350860,0.000000,0.000000,0.000000,0.392951,0.000000,0.359613,0.247191,0.000000,0.103484,0.000000,0.000000,0.0,0.000000,0.236683,0.000000,0.315176,0.142393,0.693943,0.000000,0.472984,0.482757,0.000000,0.586614,0.000000,0.000000,0.000000,0.174191,0.000000,0.0,0.270800,0.0,0.987366,0.000000,0.0,0.0,0.002269,0.155725,0.347435,0.126912,0.000000,0.0,0.328127,0.474221,0.803015
1,0.174817,0.000000,0.000000,0.331821,0.042557,0.055295,0.178387,0.133073,0.030834,0.000000,0.000000,0.258931,0.017775,0.166245,0.000000,0.000000,0.000000,0.0,0.042010,0.184471,0.000000,0.000000,0.192047,0.128010,0.000000,0.060622,0.188319,0.000000,0.229852,0.158077,0.000000,0.026753,0.000000,0.000000,0.0,0.006779,0.0,0.100961,0.000000,0.0,0.0,0.069550,0.135377,0.152882,0.000000,0.128752,0.0,0.000000,0.023388,0.231265
2,0.352621,0.177834,0.000000,0.206348,0.000000,0.386115,0.008277,0.000000,0.000000,0.433186,0.000000,0.641678,0.316970,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.212433,0.079249,0.102187,0.205542,0.546752,0.000000,0.618999,0.312516,0.000000,0.433579,0.000000,0.000000,0.000000,0.094578,0.000000,0.0,0.089261,0.0,0.814596,0.000000,0.0,0.0,0.000000,0.000000,0.365476,0.195378,0.000000,0.0,0.356269,0.574312,0.983758
3,0.389616,0.023743,0.000000,0.114516,0.000000,0.340686,0.000000,0.000000,0.000000,0.238194,0.000000,0.643828,0.540090,0.000000,0.139290,0.000000,0.000000,0.0,0.047336,0.047510,0.168050,0.232460,0.000000,0.650775,0.000000,0.674088,0.332188,0.000000,0.563356,0.000000,0.000000,0.000000,0.169112,0.000000,0.0,0.106788,0.0,1.202459,0.000000,0.0,0.0,0.009452,0.278565,0.571029,0.292291,0.000000,0.0,0.518343,0.476744,1.035461
4,0.288584,0.000000,0.300084,0.434918,0.097136,0.535571,0.000000,0.000000,0.220726,0.145732,0.563511,0.189768,0.159606,0.266432,0.201675,0.063132,0.195385,0.0,0.000000,0.078221,0.234417,0.325195,0.364693,0.599160,0.000000,0.362777,0.877191,0.000000,0.248207,0.066224,0.290777,0.529818,0.000000,0.155053,0.0,0.470593,0.0,0.399220,0.000000,0.0,0.0,0.000000,0.325236,0.012272,0.000000,0.000000,0.0,0.000000,0.019105,0.171800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4745,0.518990,0.000000,0.000000,0.363405,0.000000,0.618037,0.000000,0.000000,0.000000,0.558983,0.594196,0.607679,0.621902,0.272125,0.468298,0.000000,0.000000,0.0,0.000000,0.377823,0.711095,0.000000,0.369315,0.780995,0.000000,0.569783,0.805108,0.000000,0.549418,0.000000,0.458929,0.652980,0.000000,0.308970,0.0,0.586599,0.0,0.183667,0.000000,0.0,0.0,0.015549,0.017246,0.820472,0.000000,0.000000,0.0,0.000000,0.000000,0.378052
4746,0.191993,0.000000,0.000000,0.090170,0.252486,0.474814,0.137959,0.000000,0.387510,0.539827,0.596368,0.591892,0.373941,0.196339,0.066984,0.000000,0.145040,0.0,0.000000,0.015546,0.227457,0.043341,0.175988,0.395094,0.000000,0.627497,0.793700,0.000000,0.330209,0.109342,0.334225,0.676789,0.027540,0.327074,0.0,0.457848,0.0,0.309384,0.000000,0.0,0.0,0.139792,0.098127,0.096494,0.000000,0.000000,0.0,0.000000,0.000000,0.227425
4747,0.173208,0.000000,0.048281,0.108163,0.209472,0.338037,0.062482,0.036864,0.268231,0.488471,0.428881,0.513049,0.161629,0.112406,0.123820,0.000000,0.129489,0.0,0.000000,0.049439,0.360166,0.136330,0.127638,0.385132,0.000000,0.549603,0.549338,0.000000,0.143857,0.000000,0.132535,0.556069,0.000000,0.225932,0.0,0.432373,0.0,0.174285,0.049567,0.0,0.0,0.198764,0.112609,0.183737,0.000000,0.000000,0.0,0.000000,0.000000,0.242191
4748,0.608355,0.000000,0.310066,0.429127,0.332181,0.471315,0.140964,0.028868,0.086111,0.736760,0.780393,0.368010,0.429791,0.479073,0.218099,0.000000,0.000000,0.0,0.000000,0.169645,0.430469,0.699878,0.390542,0.599373,0.000000,0.542451,0.958209,0.087075,0.509846,0.000000,0.002166,0.968874,0.000000,0.164529,0.0,0.547132,0.0,0.336967,0.000000,0.0,0.0,0.066850,0.142725,0.038009,0.158218,0.000000,0.0,0.073220,0.281109,0.000000
4749,0.154626,0.000000,0.000000,0.455190,0.316226,0.515014,0.007497,0.000000,0.283614,1.077873,0.684822,0.458351,0.951042,0.480002,0.783643,0.000000,0.037409,0.0,0.000000,0.040709,0.554448,0.000000,0.280624,0.379101,0.006532,0.578315,0.642310,0.000000,0.530245,0.309123,0.623625,0.816513,0.340042,0.364993,0.0,0.485837,0.0,0.464236,0.000000,0.0,0.0,0.018981,0.092809,0.489854,0.000000,0.000000,0.0,0.000000,0.000000,0.470235

In [17]:
train_scaled = encoded_df[:-m_test].copy()
train_scaled['y'] = train['y']
test_scaled = encoded_df[-m_test:].copy()
train_scaled.shape, test_scaled.shape

((3865, 51), (890, 50))

In [18]:
train_scaled.to_csv('./outputs/autoenc_scaled_train2.csv', index=False)
test_scaled.to_csv('./outputs/autoenc_scaled_test2.csv', index=False)